### ISSUE TITLE
Quelques corrections "esthétiques"

### ISSUE THREAD

**Issue by DarKOrange75** [saniho/content-card-maree#5]
Bonsoir,

Juste quelques corrections de sens et esthétiques :

- Mettre Heure plutôt que date 
- Mettre des Majuscules en début de ligne
- Mettre des accents la où il faut

merci :-)

**Comment by saniho** [comment]
Merci ,j'ai mis à jour dans la dernière version

**Comment by DarKOrange75** [comment]
Merci :-)
